### ISSUE TITLE
Add github actions to the repo

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/fldgen#37]
Add github actions to the repo so that when features are added there is automated testing when PRs are opened.

**Comment by abigailsnyder** [comment]
See https://github.com/JGCRI/fldgen/issues/26 for some previous notes on travis timeouts - they're due to building the vignettes.
If we're just running into timeouts once we resolve all the other issues/errors we're seeing currently, then we can think about doing this. Maybe cutting down the test data for fewer years or just including test data on coarser resolution or something. But if we get to a point where we can run tests without issues without cutting down the test data size, then I'd say that issue is low-priority.

**Comment by kdorheim** [comment]
adding github action testing was complete with #39
